Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |v|
    v.linked_clone = true
    v.check_guest_additions = false
    v.functional_vboxsf = false
  end
  
  # plugin conflict
  if Vagrant.has_plugin?("vagrant-vbguest") then
    config.vbguest.auto_update = false
  end

  config.vm.define "strasbourg.europe" do |strasbourg|
    strasbourg.vm.box = "debian/bullseye64"
    strasbourg.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", 512]
        vb.customize ["modifyvm", :id, "--cpus", 1]
        vb.customize ["modifyvm", :id, "--cpuexecutioncap", 100]
        vb.customize ["modifyvm", :id, "--name", "strasbourg.europe"]
    end
    strasbourg.vm.network "private_network", ip: "192.168.10.141"
  end

  config.vm.define "paris.europe" do |paris|
    paris.vm.box = "debian/bullseye64"
    paris.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", 2560]
        vb.customize ["modifyvm", :id, "--cpus", 2]
        vb.customize ["modifyvm", :id, "--cpuexecutioncap", 100]
        vb.customize ["modifyvm", :id, "--name", "paris.europe"]
    end
    paris.vm.network "private_network", ip: "192.168.10.52"
  end

  config.vm.define "berlin.europe" do |berlin|
    berlin.vm.box = "debian/bullseye64"
    berlin.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", 2560]
        vb.customize ["modifyvm", :id, "--cpus", 2]
        vb.customize ["modifyvm", :id, "--cpuexecutioncap", 100]
        vb.customize ["modifyvm", :id, "--name", "berlin.europe"]
    end
    berlin.vm.network "private_network", ip: "192.168.10.55"
  end

  config.vm.define "roma.europe" do |roma|
    roma.vm.box = "debian/bullseye64"
    roma.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", 2560]
        vb.customize ["modifyvm", :id, "--cpus", 2]
        vb.customize ["modifyvm", :id, "--cpuexecutioncap", 100]
        vb.customize ["modifyvm", :id, "--name", "roma.europe"]
    end
    roma.vm.network "private_network", ip: "192.168.10.67"
  end

  config.vm.define "lisboa.europe" do |lisboa|
    lisboa.vm.box = "debian/bullseye64"
    lisboa.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", 1536]
        vb.customize ["modifyvm", :id, "--cpus", 2]
        vb.customize ["modifyvm", :id, "--cpuexecutioncap", 100]
        vb.customize ["modifyvm", :id, "--name", "lisboa.europe"]
    end
    lisboa.vm.network "private_network", ip: "192.168.10.91"
  end

  config.vm.define "madrid.europe" do |madrid|
    madrid.vm.box = "debian/bullseye64"
    madrid.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", 1536]
        vb.customize ["modifyvm", :id, "--cpus", 2]
        vb.customize ["modifyvm", :id, "--cpuexecutioncap", 100]
        vb.customize ["modifyvm", :id, "--name", "madrid.europe"]
    end
    madrid.vm.network "private_network", ip: "192.168.10.92"
  end

  config.vm.define "amsterdam.europe" do |amsterdam|
    amsterdam.vm.box = "debian/bullseye64"
    amsterdam.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", 1536]
        vb.customize ["modifyvm", :id, "--cpus", 2]
        vb.customize ["modifyvm", :id, "--cpuexecutioncap", 100]
        vb.customize ["modifyvm", :id, "--name", "amsterdam.europe"]
    end
    amsterdam.vm.network "private_network", ip: "192.168.10.93"
  end

end
