Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |v|
    v.linked_clone = true
    v.check_guest_additions = false
    v.functional_vboxsf = false
  end

  # plugin conflict
  if Vagrant.has_plugin?("vagrant-vbguest") then
    config.vbguest.auto_update = false
  end

  config.vm.define "strasbourg.europe" do |strasbourg|
    strasbourg.vm.box = "debian/buster64"
    strasbourg.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", 384]
        vb.customize ["modifyvm", :id, "--cpus", 1]
        vb.customize ["modifyvm", :id, "--cpuexecutioncap", 50]
        vb.customize ["modifyvm", :id, "--name", "strasbourg.europe"]
        vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
        vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
        vb.customize ["modifyvm", :id, "--nictype3", "virtio"]
        vb.customize ["modifyvm", :id, "--nic2", "hostonly"]
    end
    strasbourg.vm.network "private_network", ip: "192.168.10.254"
  end

  config.vm.define "paris.europe" do |paris|
    paris.vm.box = "debian/buster64"
    paris.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", 4096]
        vb.customize ["modifyvm", :id, "--cpus", 1]
        vb.customize ["modifyvm", :id, "--cpuexecutioncap", 100]
        vb.customize ["modifyvm", :id, "--name", "paris.europe"]
        vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
        vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
        vb.customize ["modifyvm", :id, "--nic2", "hostonly"]
    end
    paris.vm.network "private_network", ip: "192.168.10.10"
  end

  config.vm.define "roma.europe" do |roma|
    roma.vm.box = "debian/buster64"
    roma.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", 4096]
        vb.customize ["modifyvm", :id, "--cpus", 1]
        vb.customize ["modifyvm", :id, "--cpuexecutioncap", 100]
        vb.customize ["modifyvm", :id, "--name", "roma.europe"]
        vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
        vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
        vb.customize ["modifyvm", :id, "--nic2", "hostonly"]
    end
    roma.vm.network "private_network", ip: "192.168.10.12"
  end

  config.vm.define "madrid.europe" do |madrid|
    madrid.vm.box = "debian/buster64"
    madrid.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", 4096]
        vb.customize ["modifyvm", :id, "--cpus", 1]
        vb.customize ["modifyvm", :id, "--cpuexecutioncap", 100]
        vb.customize ["modifyvm", :id, "--name", "madrid.europe"]
        vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
        vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
        vb.customize ["modifyvm", :id, "--nic2", "hostonly"]
    end
    madrid.vm.network "private_network", ip: "192.168.10.13"
  end

  config.vm.define "lisboa.europe" do |lisboa|
    lisboa.vm.box = "debian/buster64"
    lisboa.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", 4096]
        vb.customize ["modifyvm", :id, "--cpus", 1]
        vb.customize ["modifyvm", :id, "--cpuexecutioncap", 100]
        vb.customize ["modifyvm", :id, "--name", "lisboa.europe"]
        vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
        vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
        vb.customize ["modifyvm", :id, "--nic2", "hostonly"]
    end
    lisboa.vm.network "private_network", ip: "192.168.10.14"
  end

end
