Vagrant.configure("2") do |config|

  config.vm.provider "libvirt" do |v|
  end

  config.vm.define "paris.europe" do |paris|
    paris.vm.box = "debian/buster64"
    paris.vm.provider "libvirt" do |libvirt|
      libvirt.cpus = 4
      libvirt.memory = 4096
    end
    paris.vm.network "private_network", ip: "192.168.10.10"
  end

  config.vm.define "berlin.europe" do |berlin|
    berlin.vm.box = "debian/buster64"
    berlin.vm.provider "libvirt" do |libvirt|
      libvirt.cpus = 2
      libvirt.memory = 4096
    end
    berlin.vm.network "private_network", ip: "192.168.10.11"
  end

  config.vm.define "roma.europe" do |roma|
    roma.vm.box = "debian/buster64"
    roma.vm.provider "libvirt" do |libvirt|
      libvirt.cpus = 2
      libvirt.memory = 4096
    end
    roma.vm.network "private_network", ip: "192.168.10.12"
  end

end
