Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |v|
    v.linked_clone = true
    v.check_guest_additions = false
    v.functional_vboxsf = false
  end

  # plugin conflict
  if Vagrant.has_plugin?("vagrant-vbguest") then
    config.vbguest.auto_update = false
  end

  config.vm.define "paris.europe" do |paris|
    paris.vm.box = "debian/buster64"
    paris.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", 2048]
        vb.customize ["modifyvm", :id, "--cpus", 2]
        vb.customize ["modifyvm", :id, "--cpuexecutioncap", 100]
        vb.customize ["modifyvm", :id, "--name", "paris.europe"]
        vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
        vb.customize ["modifyvm", :id, "--nic2", "intnet"]
    end
    paris.vm.network "private_network", ip: "192.168.10.10"
  end

  config.vm.define "berlin.europe" do |berlin|
    berlin.vm.box = "debian/buster64"
    berlin.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", 2048]
        vb.customize ["modifyvm", :id, "--cpus", 1]
        vb.customize ["modifyvm", :id, "--cpuexecutioncap", 100]
        vb.customize ["modifyvm", :id, "--name", "berlin.europe"]
        vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
        vb.customize ["modifyvm", :id, "--nic2", "intnet"]
    end
    berlin.vm.network "private_network", ip: "192.168.10.11"
  end

  config.vm.define "roma.europe" do |roma|
    roma.vm.box = "debian/buster64"
    roma.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", 2048]
        vb.customize ["modifyvm", :id, "--cpus", 1]
        vb.customize ["modifyvm", :id, "--cpuexecutioncap", 100]
        vb.customize ["modifyvm", :id, "--name", "roma.europe"]
        vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
        vb.customize ["modifyvm", :id, "--nic2", "intnet"]
    end
    roma.vm.network "private_network", ip: "192.168.10.12"
  end

end
